### ISSUE TITLE
[quick test enhancement] IP save file

### ISSUE THREAD

**Issue by yorshex** [Smashing-Tech/Smash-Hit-Blender-Tools#48]
Since we can actually get `package`, `io`, and `os` modules working in smash hit script files why not to add a button that'll set the ip address in `/data/data/org.knot126.quicktestclient/quicktestdomain.txt` and then read the ip from this file when you press start button so you don't have to manually edit quick test client apk to get it working with your ip address?

**Comment by knot126** [comment]
I am probably going to do this but note it won't be a feature on ARM32 versions of the game.

**Comment by knot126** [comment]
Done in 3.2.0
