### ISSUE TITLE
[enhancement] add a setting to specify the default path to `templates.xml.mp3`

### ISSUE THREAD

**Issue by yorshex** [Smashing-Tech/Smash-Hit-Blender-Tools#50]
i don't edit an apk to make my mod, i just save all the mod files in their own assets directory and merge apk assets and mod assets every time i need to make a modded apk. but shbt always assume that you have apk editor studio opened and sets the templates path to the one that's located in apk editor studio tmp directory. this forces me to set templates path manually every time i open and export a segment

this problem can be solved by adding templates default path in shbt settings

idk if other ppl are having the problem, so it's not that necessary to solve

**Comment by knot126** [comment]
The templates path has been added, will test the next batch of changes soon and hope to make a 2.1.7 release within the next few hours.
